// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types generate

export interface AbilityDefinition {
  key: string;
  name: string;
  affinity: string;
  energyCost: number;
  cooldownTurns: number;
  targetingType?: string;
  effectConfig: {};
  enabled: boolean;
  version: string;
}

export interface Architect {
  userId: string;
  scoreCalculationId: string;
  level: number;
  experience: number;
  powerBand?: string;
  force: number;
  guard: number;
  momentum: number;
  precision: number;
  insight: number;
  primaryAffinity?: string;
  secondaryAffinities?: string[];
  /**
   * @maxItems 3
   */
  activeAbilityIds?: [] | [string] | [string, string] | [string, string, string];
  /**
   * @maxItems 2
   */
  passiveTraitIds?: [] | [string] | [string, string];
  artifactId?: string;
  buildVersion: number;
  updatedAt: string;
}

export interface ArtifactDefinition {
  key: string;
  name: string;
  rarity: string;
  effectConfig: {};
  enabled: boolean;
  version: string;
}

export interface AuditLog {
  userId?: string;
  action: string;
  entityType: string;
  entityId: string;
  correlationId: string;
  metadata?: {};
  createdAt: string;
}

export interface Challenge {
  challengerUserId: string;
  challengedUserId?: string;
  shareCode: string;
  challengeType: "dungeon_score" | "architect_compare";
  challengerSnapshot: {};
  status: "open" | "accepted" | "completed" | "expired" | "cancelled";
  expiresAt: string;
  acceptedAt?: string;
  completedAt?: string;
  result?: {};
}

export interface CombatTurn {
  userId: string;
  dungeonRunId: string;
  turnNumber: number;
  idempotencyKey: string;
  playerAction: {};
  enemyAction?: {};
  randomValues?: number[];
  stateBeforeHash: string;
  stateAfter: {};
  stateAfterHash: string;
  combatLog: string[];
  resolvedAt: string;
}

export interface DungeonDefinition {
  key: string;
  name: string;
  version: string;
  roomConfig: {}[];
  rewardConfig: {};
  enabled: boolean;
}

export interface DungeonRun {
  userId: string;
  dungeonDefinitionId: string;
  dungeonVersion: string;
  seed: string;
  status: "active" | "completed" | "failed";
  currentRoomIndex: number;
  currentTurn: number;
  health: number;
  maxHealth: number;
  energy: number;
  guardMeter?: number;
  momentumChain?: number;
  statusEffects?: {}[];
  statePayload?: {};
  buildSnapshot: {};
  calculationVersion: string;
  rewardStatus: "pending" | "issued" | "ineligible";
  startedAt: string;
  completedAt?: string;
  lastActionAt?: string;
}

export interface Faction {
  key: string;
  name: string;
  primaryAffinity: string;
  totalInfluence: number;
  currentSeasonId: string;
  createdAt: string;
}

export interface GitHubConnection {
  userId: string;
  provider: "github";
  connectionStatus: "connected" | "invalid" | "disconnected";
  encryptedCredentialReference?: string;
  grantedScopes?: string[];
  connectedAt?: string;
  disconnectedAt?: string;
  lastValidatedAt?: string;
}

export interface GitHubSnapshot {
  userId: string;
  capturedAt: string;
  accountCreatedAt?: string;
  accountAgeDays?: number;
  publicRepoCount?: number;
  meaningfulRepoCount?: number;
  totalVerifiedCommits?: number;
  recentVerifiedCommits?: number;
  currentStreakDays?: number;
  longestStreakDays?: number;
  activeWeeksLastYear?: number;
  consistencyScoreInput?: number;
  pullRequestsOpened?: number;
  pullRequestsMerged?: number;
  externalPullRequestsMerged?: number;
  releasesCount?: number;
  maintainedRepoCount?: number;
  languageDistribution?: {
    [k: string]: number | undefined;
  };
  rawMetricSummary?: {};
  sourceVersion: string;
  snapshotHash: string;
  isCurrent: boolean;
}

export interface GitHubSyncJob {
  userId: string;
  status: "queued" | "running" | "completed" | "failed";
  requestedAt: string;
  startedAt?: string;
  completedAt?: string;
  errorCode?: string;
  rateLimitResetAt?: string;
  lockExpiresAt?: string;
  correlationId: string;
}

export interface InfluenceLedger {
  userId: string;
  factionId: string;
  territoryId: string;
  dungeonRunId: string;
  amount: number;
  actionType: "attack" | "defend" | "raid";
  idempotencyKey: string;
  committedAt: string;
}

export interface LeaderboardEntry {
  userId: string;
  seasonId: string;
  category: "dungeon_score" | "seasonal_rating" | "faction_contribution" | "rare_traits" | "streak";
  score: number;
  rank: number;
  sourceVersion: string;
  publicProfile: {};
  updatedAt: string;
}

export interface PlayerArtifact {
  userId: string;
  artifactDefinitionId: string;
  quantity: number;
  acquiredAt: string;
  sourceType: string;
  sourceId: string;
}

export interface PlayerTrait {
  userId: string;
  traitDefinitionId: string;
  snapshotId: string;
  evidence: {};
  unlockedAt: string;
  active: boolean;
}

export interface RewardLedger {
  userId: string;
  sourceType: string;
  sourceId: string;
  rewardType: "experience" | "seasonal_rating" | "influence" | "artifact" | "cosmetic" | "achievement";
  amount: number;
  metadata?: {};
  idempotencyKey: string;
  issuedAt: string;
}

export interface ScoreCalculation {
  userId: string;
  snapshotId: string;
  calculationVersion: string;
  formulaConfigId?: string;
  forcePotential?: number;
  guardPotential?: number;
  momentumPotential?: number;
  precisionPotential?: number;
  insightPotential?: number;
  totalForgePoints: number;
  primaryAffinity?: string;
  secondaryAffinities?: string[];
  normalizedMetrics?: {};
  appliedCaps?: {};
  explanation?: {}[];
  inputHash: string;
  calculatedAt: string;
}

export interface SuspiciousActivityFlag {
  userId: string;
  category: string;
  severity: "low" | "medium" | "high" | "critical";
  evidence: {};
  status: "open" | "reviewing" | "resolved" | "dismissed";
  createdAt: string;
  reviewedAt?: string;
}

export interface Territory {
  key: string;
  name: string;
  ownerFactionId?: string;
  attackInfluenceByFaction: {
    [k: string]: number | undefined;
  };
  defenceInfluence: number;
  activeModifier: {};
  stateVersion: number;
  currentSeasonId: string;
  resolvesAt: string;
  updatedAt: string;
}

export interface TraitDefinition {
  key: string;
  name: string;
  description: string;
  rarity?: string;
  criteriaVersion: string;
  combatEffectConfig?: {};
  enabled: boolean;
}

export interface UserProfile {
  userId: string;
  githubLogin?: string;
  githubUserId?: string;
  githubAvatarUrl?: string;
  onboardingStatus: "account" | "github_pending" | "syncing" | "profile_ready" | "architect_ready";
  factionId?: string;
  currentSeasonId?: string;
  displayName?: string;
  createdAt: string;
  updatedAt: string;
}

declare module '@base44/sdk' {
  interface EntityTypeRegistry {
    "AbilityDefinition": AbilityDefinition;
    "Architect": Architect;
    "ArtifactDefinition": ArtifactDefinition;
    "AuditLog": AuditLog;
    "Challenge": Challenge;
    "CombatTurn": CombatTurn;
    "DungeonDefinition": DungeonDefinition;
    "DungeonRun": DungeonRun;
    "Faction": Faction;
    "GitHubConnection": GitHubConnection;
    "GitHubSnapshot": GitHubSnapshot;
    "GitHubSyncJob": GitHubSyncJob;
    "InfluenceLedger": InfluenceLedger;
    "LeaderboardEntry": LeaderboardEntry;
    "PlayerArtifact": PlayerArtifact;
    "PlayerTrait": PlayerTrait;
    "RewardLedger": RewardLedger;
    "ScoreCalculation": ScoreCalculation;
    "SuspiciousActivityFlag": SuspiciousActivityFlag;
    "Territory": Territory;
    "TraitDefinition": TraitDefinition;
    "UserProfile": UserProfile;
  }
  
  interface FunctionNameRegistry {
    "acceptChallenge": true;
    "calculateForgePoints": true;
    "awardDungeonRewards": true;
    "createChallenge": true;
    "commitTerritoryInfluence": true;
    "getAdminAudit": true;
    "getGitHubSyncStatus": true;
    "getLeaderboard": true;
    "getPublicChallenge": true;
    "getWorldState": true;
    "refreshLeaderboards": true;
    "resolveTerritories": true;
    "saveArchitectBuild": true;
    "selectFaction": true;
    "startDungeonRun": true;
    "submitCombatAction": true;
    "syncGitHubProfile": true;
  }
}